### ISSUE TITLE
gas price is 0

### ISSUE THREAD

**Issue by lsdbitrue** [flare-foundation/flare#18]
```console
$ curl --location --request POST 'http://127.0.0.1:9650/ext/bc/C/rpc' --header 'Content-Type: application/json' --data-raw '{
"id": "1",
"jsonrpc": "2.0",
"method": "eth_gasPrice",
"params": []
}'
{"jsonrpc":"2.0","id":"1","result":"0x0"}
```

Node version: 0.5.1

**Comment by awfm9** [comment]
Hi @lsdbitrue, and thank you for the bug report.

This is indeed not expected behaviour. I found that this is indeed an upstream bug, originating in the Ethereum code base, and trickling down to Flare through the Avalanche Coreth implementation.

I implemented a small fix to work around the issue, which should give you the correct gas price estimates. You can find it in the `v0.5.2` release I just tagged.

**If you are curious about how this went unnoticed for the other projects:**

The reason that this never came up for the upstream projects is that the price oracle code was improved _after_ the first dynamic fees hard fork was rolled out (_London_ on Ethereum, _Apricot Phase 3_ on Avalanche). This means that they never had a situation where this oracle code was active, but base fees were not yet available.

The new oracle code adds the _base fee_ to the _priority fee_ (tip), and returns that as the legacy _gas price_. This works fine as long as there is a base fee. However, on networks where the base fee has not been activated yet, it will lead to a gas price estimate equal to the priority fee (tip), which is zero when blocks are mostly empty.

Flare is currently still on the pre-dynamic fees hard fork, even though we have the latest oracle code already, which triggers this bug. The issue would have disappeared by itself once the first hard fork is activated, just like it never showed up on the other upstream project networks.
