### ISSUE TITLE
Detect arbitrary rejection of payments

### ISSUE THREAD

**Issue by awfm9** [flare-foundation/flare#7]

**Comment by ilanDoron** [comment]
For full support of of the fAsset system. we need the ability to detect a blocked payment. 
## background
in different flows, the party receiving a payment (Ex: Minter or Agent) could provide an address that has payments blocked. in this case the receiving side might claim the payment wasn't received and force the sending side to pay a penalty fee.

#details
thus there must be support to detect per failed payment if it has failed due to:
-  a sender issue:
    -  ex: not enough gas
-  a receiver issue:
   -  contract blocking payments on EVM chains
   - address blocked for payments on XRP chains.
   - T.B.D on other chains
